Class {
	#name : 'WASWGettingStartedPage',
	#superclass : 'WASWPage',
	#category : 'Seaside-Website-UI-Pages',
	#package : 'Seaside-Website-UI',
	#tag : 'Pages'
}

{ #category : 'rendering' }
WASWGettingStartedPage class >> pageDetail [

	^ 'Download and Install'
]

{ #category : 'rendering' }
WASWGettingStartedPage class >> pageTitle [

	^ 'Get Started'
]

{ #category : 'rendering' }
WASWGettingStartedPage >> pageCssClass [

	^ 'documentation-page'
]

{ #category : 'rendering' }
WASWGettingStartedPage >> renderContentOn: html [


]
