Class {
	#name : 'WASWCommunityPage',
	#superclass : 'WASWPage',
	#category : 'Seaside-Website-UI-Pages',
	#package : 'Seaside-Website-UI',
	#tag : 'Pages'
}

{ #category : 'rendering' }
WASWCommunityPage class >> pageDetail [

	^ 'Get involved'
]

{ #category : 'rendering' }
WASWCommunityPage class >> pageTitle [

	^ 'Community'
]

{ #category : 'rendering' }
WASWCommunityPage >> pageCssClass [

	^ 'documentation-page'
]
